spring:
 cloud:
  stream:
   kafka:
    binder:
     brokers: keycloak.graeshoppe.divisotech.com:9092
   bindings:
    productCreation:
     destination: ProductCreation
     contentType: application/json
    saleEvent:
     destination: SaleEventTopic
     contentType: application/json  
    customerRegistration:
     destination: CustomerRegistrationTopic
     contentType: application/json	
    employeeRegistration:
     destination: EmployeeRegistrationTopic
     contentType: application/json