spring:
 cloud:
  stream:
   kafka:
    binder:
     brokers: keycloak.graeshoppe.divisotech.com:9092
   bindings:
    productoutput:
     destination: ProductTopic
     contentType: application/json
    saleoutput:
     destination: SaleTopic
     contentType: application/json  
    registrationoutput:
     destination: RegistrationTopic
     contentType: application/json
    paymentoutput:
     destination: PaymentTopic
     contentType: application/json	
    customerInput:
     destination: RegistrationStatusTopic
     contentType: application/json